#Updated BaseURI dynamically
#Fri Feb 14 14:52:41 IST 2025
columns.subOptions=Full Name,Random,Email Address,Product ID
rows.count=5
chrome.driver.path=drivers/chromedriver.exe
edge.driver.path=drivers/msedgedriver.exe
browser=chrome
columns.options=People,Numbers,People,Numbers
columns.count=4
columns.names=Name,OrdersCount,Email,ProducID
firefox.driver.path=drivers/geckodriver.exe
url=https://retool.com/api-generator
BaseURI=https://retoolapi.dev/a3IAYp/data
