rows.count=5
columns.subOptions=Full Name,Random,Email Address,Product ID
chrome.driver.path=drivers/chromedriver.exe
edge.driver.path=drivers/msedgedriver.exe
browser=chrome
response.file.name=order.json
columns.options=People,Numbers,People,Numbers
columns.count=4
columns.names=Name,OrdersCount,Email,ProducID
url=https://retool.com/api-generator
firefox.driver.path=drivers/geckodriver.exe
BaseURI=https://retoolapi.dev/O3EloE/data
